import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './global.scss';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <html lang="ru">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
